"""Generates lib/shortCodeFont.ts: the short-code alphabet as 1-bit glyphs (ONE-144).

Printed tag images are 1-bit PNGs drawn by hand (lib/png.ts), with no text
rendering, so the short code printed under each code is drawn from this table.
The glyphs are DM Mono Medium, the face the app sets short codes in on screen
(theme/tokens.ts, type.mono), rasterised once at SIZE pixels and thresholded.

Only the 57 characters a short code can hold (TAG_SHORT_CODE_ALPHABET in
lib/tagLinks.ts) are drawn. Re-run after changing the alphabet or the size:

    python scripts/generate-short-code-font.py

Needs Pillow. The output is committed, so the app and its tests never need it.
"""
import os

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT = os.path.join(ROOT, 'node_modules', '@expo-google-fonts', 'dm-mono', '500Medium', 'DMMono_500Medium.ttf')
OUT = os.path.join(ROOT, 'lib', 'shortCodeFont.ts')

# lib/tagLinks.ts's TAG_SHORT_CODE_ALPHABET; __tests__/lib/bitmapText.test.ts checks they agree.
ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789'
# The type size, in pixels: about 2.9 mm cap height at 300 dpi.
SIZE = 48

font = ImageFont.truetype(FONT, SIZE)
advance = round(font.getlength('M'))
ascent, descent = font.getmetrics()
height = ascent + descent


def raster(char):
    im = Image.new('L', (advance, height), 0)
    ImageDraw.Draw(im).text((0, ascent), char, font=font, fill=255, anchor='ls')
    return [[im.getpixel((x, y)) >= 128 for x in range(advance)] for y in range(height)]


glyphs = {char: raster(char) for char in ALPHABET}

# Crop the rows no glyph inks, top and bottom, the same for every glyph.
inked = [y for y in range(height) if any(any(g[y]) for g in glyphs.values())]
top, bottom = inked[0], inked[-1] + 1
digits = (advance + 3) // 4


def hex_row(row):
    bits = ''.join('1' if on else '0' for on in row).ljust(digits * 4, '0')
    return format(int(bits, 2), f'0{digits}x')


lines = [
    '// GENERATED by scripts/generate-short-code-font.py — do not edit by hand (ONE-144).',
    '//',
    '// The short-code alphabet as 1-bit glyphs, DM Mono Medium rasterised at',
    f'// {SIZE}px. Each glyph is {advance} pixels wide and {bottom - top} tall; each row is',
    '// hex, most significant bit leftmost, a set bit ink.',
    '',
    'export const SHORT_CODE_FONT = {',
    f'  size: {SIZE},',
    f'  width: {advance},',
    f'  height: {bottom - top},',
    '  glyphs: {',
]
for char in ALPHABET:
    rows = ', '.join(f"'{hex_row(r)}'" for r in glyphs[char][top:bottom])
    lines.append(f"    {char}: [{rows}],")
lines += ['  } as Record<string, readonly string[]>,', '} as const;', '']

with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(lines))
print(f'wrote {OUT}: {len(ALPHABET)} glyphs, {advance}x{bottom - top}')
